* Requirements
Packages from melpa should be automatically downloaded, thanks to
use-package. There are however, couple of packages and snippets which
are not in any package repository. They need to be downloaded manually
first. Ideally, I want these stuff to be bootstraped like the rest
with some magic. Here is the list of stuff that need to be downloaded
manually first:

** ispell (osx only)
Install ispell by ~brew install ispell --with-lang-en~ (taken from
[[https://unix.stackexchange.com/a/84514/56144][this]] page).
** personal material theme

** move-lines
~git clone https://github.com/targzeta/move-lines.git~ and also don't
forget to add correct path down below.

** more?


* Global emacs configurations
** Interface

X-Bars
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
  (tool-bar-mode -1)
  (show-paren-mode 1)
  (menu-bar-mode -1)
#+END_SRC

Disable startup screen
#+BEGIN_SRC emacs-lisp
  (setq inhibit-splash-screen t)
  (setq inhibit-startup-message t)
#+END_SRC

Deafult startup directory
#+BEGIN_SRC emacs-lisp
  (setq default-directory "~/.emacs.d/")
#+END_SRC

Shortcut for `ffap`
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "s-f") 'ffap)
#+END_SRC

For detecting new lines, add the following otherwise text or tex or similar wouldn't navigate to the
EOL but rather to end of the paragraph.
#+BEGIN_SRC emacs-lisp
  (setq sentence-end-double-space nil)
#+END_SRC

Set cursor as bar
#+BEGIN_SRC emacs-lisp
  (setq-default cursor-type 'bar)
#+END_SRC

Focus to help window so that after, e.g., ~descrive-variable~, I could hit ~q~ to exit easily:
#+BEGIN_SRC emacs-lisp
  (setq help-window-select 1)
#+END_SRC

Overwrite/delete selection as you type
#+BEGIN_SRC emacs-lisp
  (delete-selection-mode 1)
#+END_SRC

Hilight current line
#+BEGIN_SRC emacs-lisp
  (global-hl-line-mode 1)
#+END_SRC

** Window navigation
#+BEGIN_SRC emacs-lisp
  (windmove-default-keybindings 'meta)
#+END_SRC

** buffer menu
Use ibuffer with shortcut similar to sublime
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-S-p") 'ibuffer)

#+END_SRC

** move-lines
#+BEGIN_SRC emacs-lisp
  (add-to-list 'load-path "~/.emacs.d/etc/move-lines")
  (require 'move-lines)
  (global-set-key (kbd "<C-S-up>") 'move-lines-up)
  (global-set-key (kbd "<C-S-down>") 'move-lines-down)
#+END_SRC

** tab-size
#+BEGIN_SRC emacs-lisp
  ;(setq tab-width 4) ; or any other preferred value
  ;(defvaralias 'c-basic-offset 'tab-width)
  ;(defvaralias 'cperl-indent-level 'tab-width)
#+END_SRC

** duplicate line
#+BEGIN_SRC emacs-lisp
  ; duplicate line. JESUS FUCKING CHRIST EMACS :/
  (defun duplicate-line()
    (interactive)
    (move-beginning-of-line 1)
    (kill-line)
    (yank)
    (open-line 1)
    (next-line 1)
    (yank)
  )
  (global-set-key (kbd "C-S-d") 'duplicate-line)
#+END_SRC

** ispell
(macos only)
#+BEGIN_SRC emacs-lisp
  (if (eq system-type 'darwin)
      (setq ispell-program-name "/usr/local/Cellar/ispell/3.4.00/bin/ispell")
  )
#+END_SRC

** themeing
#+BEGIN_SRC emacs-lisp
  (add-to-list 'custom-theme-load-path "~/.emacs.d/etc/yamt-theme")
  (load-theme 'yamt)
#+END_SRC


* Important packages
** Magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
#+END_SRC

** Auctex
Some info regarding auctex and use-package [[https://github.com/jwiegley/use-package/issues/379#issuecomment-246161500][here]] and [[https://github.com/jwiegley/use-package/issues/379#issuecomment-258217014][here]].
#+BEGIN_SRC emacs-lisp
  (use-package tex
    :defer t
    :ensure auctex
    :init
    (setq reftex-plug-into-AUCTeX t)  
    (setq TeX-source-correlate-mode t)
    (setq TeX-source-correlate-method 'synctex)
    :config
    (setq TeX-auto-save t)
    (setq font-latex-fontify-script nil)
    (setq TeX-error-overview-open-after-TeX-run t)
    (add-hook 'LaTeX-mode-hook
      (lambda ()
	(reftex-mode 1)
	(setq fill-column 100) ; or 80 or whatever
      )
    )
    ;; seting up pdf-tools:    
    (setq TeX-view-program-selection '((output-pdf "PDF Tools"))
      TeX-source-correlate-start-server t)
    (add-hook 'TeX-after-compilation-finished-functions
           #'TeX-revert-document-buffer)
    ;(local-set-key [C-tab] 'TeX-complete-symbol)
  )
#+END_SRC

** Bibtex
For reindent and pretty printing the bib items
#+BEGIN_SRC emacs-lisp
  (add-hook 'bibtex-mode-hook
    (lambda ()
      (setq fill-column 999999)
      (setq bibtex-align-at-equal-sign t)
      (setq fill-prefix nil)
      (local-set-key (kbd "M-q") 'bibtex-fill-entry)
    )
  )
#+END_SRC

Snippet below attempts to download bib items from a doi but needs further work ([[https://www.anghyflawn.net/blog/2014/emacs-give-a-doi-get-a-bibtex-entry/][source]]).
#+BEGIN_SRC emacs-lisp
  (defun get-bibtex-from-doi (doi)
   "Get a BibTeX entry from the DOI"
   (interactive "MDOI: ")
   (let ((url-mime-accept-string "text/bibliography;style=bibtex"))
     (with-current-buffer 
       (url-retrieve-synchronously 
	 (format "http://dx.doi.org/%s" 
	  (replace-regexp-in-string "http://dx.doi.org/" "" doi)))
       (switch-to-buffer (current-buffer))
       (goto-char (point-max))
       (setq bibtex-entry 
	    (buffer-substring 
		  (string-match "@" (buffer-string))
		(point)))
       (kill-buffer (current-buffer))))
   (insert (decode-coding-string bibtex-entry 'utf-8))
   (bibtex-fill-entry))
#+END_SRC

** multiple-cursor
#+BEGIN_SRC emacs-lisp
  (use-package multiple-cursors
    :ensure t
    :bind (("C-d" . mc/mark-next-like-this)
	   ("C-S-l" . mc/edit-lines)
	  )
  )
#+END_SRC

** expand-region
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind (("C-=" . er/expand-region))
  )
#+END_SRC

** try
#+BEGIN_SRC emacs-lisp
  (use-package try
    :ensure t)
#+END_SRC

** which key
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :config (which-key-mode)
  )
#+END_SRC
** rainbow
rainbow-mode and maybe (in the future) rainbow brackets
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :hook prog-mode)
#+END_SRC 
** decoration
Highlight numbers
#+BEGIN_SRC emacs-lisp
  (use-package highlight-numbers
    :ensure t
    :init
    (add-hook 'prog-mode-hook 'highlight-numbers-mode))
#+END_SRC
** Org mode stuff
Syntax highlighting for code blocks:
#+BEGIN_SRC emacs-lisp
  (setq org-src-fontify-natively t)
#+END_SRC

Org agenda configuration:
#+BEGIN_SRC emacs-lisp
  ;(setq org-agenda-files (list "~/Work/Agenda/january.org"
  ;			     "~/Work/Agenda/february.org"
  ;			     "~/Work/Agenda/march.org"))

  (setq org-agenda-files (quote ("~/Work/Agenda/january.org")))
#+END_SRC

Better org bullets:
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
      (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+END_SRC
** Helm
Whatever...
#+BEGIN_SRC emacs-lisp :tangle no
  (use-package helm
    :ensure t
    :bind
    ("C-x C-f" . 'helm-find-files)
    ("C-x C-b" . 'helm-mini) ; C-Up/C-Down or C-c C-f to make it permanent
    ("M-x" . 'helm-M-x)
    :init
    (helm-mode 1))
#+END_SRC

** Predictive mode
I really like this. It is fast and rather helpfull when writing text, e.g., Latex, but it is paint to install. If it is installed, then I like to use the following shortcuts. [[http://www.dr-qubit.org/predictive/predictive-user-manual/predictive-user-manual.pdf][Manual]]
#+BEGIN_SRC emacs-lisp
  (if (eq system-type 'gnu/linux)
      (progn
	(message "Setting predictive path...")
	(add-to-list 'load-path "~/.emacs.d/predictive")
	(add-to-list 'load-path "~/.emacs.d/predictive/misc")
	(add-to-list 'load-path "~/.emacs.d/predictive/latex")
	(add-to-list 'load-path "~/.emacs.d/predictive/texinfo")
	(add-to-list 'load-path "~/.emacs.d/predictive/html")
	(setq completion-ui-use-echo nil)
	(setq completion-auto-show nil)
	(require 'predictive)
	(eval-after-load 'completion-ui
	  '(define-key completion-overlay-map "\t" 'completion-accept)))
    )

#+END_SRC

** smartparens
In the future I will check paredit, but for the moment:
#+BEGIN_SRC emacs-lisp
  (use-package smartparens
    :ensure t
    ;:diminish smartparens-mode
    :config
    (progn
      (require 'smartparens-config)
      (show-smartparens-global-mode 1)
      (smartparens-global-mode 1))
    ;:bind
    ;(("bla" . fla-func)
    ; ("foo" . foo-func))
    )
#+END_SRC
** diminish
This can be done directly with the ~use-package~ but I do it like this:
#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :ensure t
    :init
    (diminish 'smartparens-mode)
    (diminish 'which-key-mode)
    (diminish 'rainbow-mode)
    (diminish 'auto-completion-mode)
    )
#+END_SRC

** pdf-tools
This one seems interesting. I will see if I can use it with latex...
#+BEGIN_SRC emacs-lisp
  (use-package pdf-tools
    :ensure t
    ; :pin manual ;; manually update taken from http://pragmaticemacs.com/emacs/more-pdf-tools-tweaks/
    :config
    (pdf-tools-install)
    ; alternatively if it becomes annoying (pdf-loader-install)
  )
#+END_SRC


* Useful snippets
** word repetition, taken from [[https://www.gnu.org/software/emacs/manual/html_node/eintr/the_002dthe.html][here]]. Although, it's a bit iffy...
#+BEGIN_SRC emacs-lisp
  (defun the-the ()
    "Search forward for for a duplicated word."
    (interactive)
    (message "Searching for for duplicated words ...")
    (push-mark)
    ;; This regexp is not perfect
    ;; but is fairly good over all:
    (if (re-search-forward
	 "\\b\\([^@ \n\t]+\\)[ \n\t]+\\1\\b" nil 'move)
	(message "Found duplicated word.")
      (message "End of buffer")))
#+END_SRC


* Packages to be considered
1. [[https://github.com/gonewest818/dimmer.el][dimmer.el]]
2. [[https://github.com/mkcms/interactive-align][ialign.el]]
